'use client';
import { Text, useLanguage } from '@/components/language-provider';
import Link from 'next/link';
import Image from 'next/image';
import daylightPortrait from '../../public/images/emilio-daylight-portrait.png';
import formalPortrait from '../../public/images/emilio-formal-portrait.png';
import { MediaPlaceholder } from '@/components/media-placeholder';
import { projects, services } from '@/content/studio';
export default function Home() {
  const { t } = useLanguage();
  return <main id="main">
    <section id="storefront" className="hero" aria-labelledby="hero-title">
      <div className="hero-topline eyebrow"><span><Text text="Independent by design." /></span><span>Miami / FL <span className="signal-dot" /></span></div>
      <div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><Text text="Creativity meets technology" /></p><h1 id="hero-title"><Text text="I CREATE" /><br /><span><Text text="WHAT’S" /></span><br /><Text text="NEXT" /><span className="cobalt">.</span></h1><div className="hero-intro"><p><Text text="I design and build digital experiences across web, graphics and video from Miami." /></p><Link href="#work" className="text-link"><Text text="Explore my work" /> <span>↓</span></Link></div></div><div className="hero-visual"><div className="hero-portrait"><Image src={daylightPortrait} alt={t("Emilio Sierra using his smartphone beside sunlit windows and tropical greenery.")} fill sizes="(max-width: 760px) 90vw, 45vw" preload placeholder="blur" /></div><p className="image-note eyebrow"><Text text="A human perspective. A forward-looking practice." /></p></div></div>
      <div className="service-directory">{services.map(s => <a href={`#service-${s.number}`} key={s.number}>{t(s.title)}<span>↘</span></a>)}</div>
    </section>
    <section id="work" className="work section-space" aria-labelledby="work-title"><div className="section-heading"><p className="eyebrow"><Text text="Selected work" /></p><h2 id="work-title"><Text text="Ideas, made real." /></h2><span className="eyebrow"><Text text="Design / Production / Experience" /></span></div>
      {projects.map((p, i) => <article className={`project project-${i}`} key={p.slug}><Link className="project-media-link" href={`/work/${p.slug}`} aria-label={`${t("Explore")} ${t(p.name)}`}>{p.image ? <Image className="project-image" src={p.image.src} alt={t(p.image.alt)} sizes="(max-width: 760px) 90vw, 60vw" placeholder="blur" /> : <MediaPlaceholder kind={i === 0 ? 'artwork' : 'broadcast'} label={t(p.media)} />}</Link><div className="project-info"><p className="eyebrow"><Text text="Project" /> <span>{t(p.discipline)}</span></p><Link href={`/work/${p.slug}`} className="project-title"><h3>{t(p.title)}</h3><span>↗</span></Link><p>{t(p.summary)}</p><Link href={`/work/${p.slug}`} className="text-link"><Text text="Explore the story" /> <span>→</span></Link></div></article>)}
    </section>
    <section id="services" className="services section-space" aria-labelledby="services-title"><div className="section-heading"><p className="eyebrow"><Text text="What I do" /></p><h2 id="services-title"><Text text="Different disciplines." /><br /><Text text="One curious mind." /></h2></div><div className="services-list">{services.map(s => <article id={`service-${s.number}`} className="service-row" key={s.number}><p className="eyebrow">{t(s.discipline)}</p><h3>{t(s.title)}</h3><div><p>{t(s.description)}</p><p className="eyebrow capabilities">{t(s.capabilities)}</p><Link href="/start-a-project" className="text-link"><Text text="Let’s talk" /> <span>↗</span></Link></div></article>)}</div></section>
    <section id="about" className="about section-space" data-environment="night" aria-labelledby="about-title"><p className="eyebrow"><Text text="The person behind the practice" /></p><div className="about-grid"><h2 id="about-title"><Text text="CURIOSITY" /><br /><Text text="MADE ME" /><br /><Text text="A CREATOR" /><span>.</span></h2><div className="about-copy"><p className="large-copy"><Text text="I’ve always been creative, and technology has always come naturally to me. Curiosity connected the two." /></p><p><Text text="Growing up, I found myself constantly reading, learning and exploring whatever captured my attention. The more I learned, the more questions I had—and eventually, those questions became things I wanted to create." /></p><p><Text text="What excites me most is the possibility of building technology that can make someone’s everyday life a little better." /></p><p className="display-copy"><Text text="Ultimately, I want to invent things." /></p><div className="about-portrait"><Image className="about-portrait-image" src={formalPortrait} alt={t("Emilio Sierra standing indoors in a white shirt, light blue tie and beige trousers.")} sizes="(max-width: 760px) 90vw, 360px" placeholder="blur" /></div><p className="eyebrow"><Text text="Creator / Designer / Developer / Producer" /></p></div></div></section>
    <section id="contact" className="contact section-space" data-environment="night" aria-labelledby="contact-title"><div className="contact-top"><p className="eyebrow"><span className="signal-dot" /><Text text="What’s next" /></p><a className="eyebrow daylight-link" href="#storefront"><Text text="Back to daylight ↑" /></a></div><h2 id="contact-title"><Text text="LET’S MAKE" /><br /><Text text="SOMETHING" /><span>.</span></h2><div className="contact-bottom"><p><Text text="Have an idea, a problem to solve, or something you want to create? Tell me about it." /></p><Link href="/start-a-project" className="text-link"><Text text="Start a project" /> <span>↗</span></Link></div></section>
  </main>;
}
