export const spanish: Record<string, string> = {
  'Send inquiry': 'Enviar consulta', 'Sending…': 'Enviando…', 'Inquiry submitted': 'Consulta enviada',
  'Your details will be used to respond to your inquiry.': 'Tus datos se usarán para responder a tu consulta.',
  'Your inquiry has been submitted. Thank you—I’ll be in touch.': 'Tu consulta se ha enviado. Gracias, me pondré en contacto contigo.',
  'Please complete this field.': 'Completa este campo.',
  'This field is too long.': 'Este campo es demasiado largo.',
  'Please enter a valid value.': 'Introduce un valor válido.',
  'Please enter a valid email address.': 'Introduce un correo electrónico válido.',
  'Choose at least one service.': 'Elige al menos un servicio.',
  'Please reload the page and try again.': 'Recarga la página e inténtalo de nuevo.',
  'Unable to submit this inquiry.': 'No se puede enviar esta consulta.',
  'Please check the highlighted fields.': 'Revisa los campos señalados.',
  'Email delivery is unavailable right now. Your inquiry has not been sent. Please try again later.': 'El envío de correo no está disponible ahora. Tu consulta no se ha enviado. Inténtalo más tarde.',
  'Too many attempts. Please try again later.': 'Demasiados intentos. Inténtalo más tarde.',
  'Your inquiry could not be sent. Please try again.': 'No se pudo enviar tu consulta. Inténtalo de nuevo.',
  'Your inquiry could not be confirmed. Please try again.': 'No se pudo confirmar el envío de tu consulta. Inténtalo de nuevo.', 
  'Independent by design.': 'Independiente por naturaleza.',
  'Creativity meets technology': 'La creatividad se une a la tecnología',
  'I CREATE': 'CREO', 'WHAT’S': 'LO QUE', 'NEXT': 'VIENE',
  'I design and build digital experiences across web, graphics and video from Miami.': 'Diseño y desarrollo experiencias digitales para web, diseño gráfico y video desde Miami.',
  'Explore': 'Explora',
  'Explore my work': 'Explora mi trabajo',
  'A human perspective. A forward-looking practice.': 'Una perspectiva humana. Una práctica que mira al futuro.',
  'Selected work': 'Trabajos seleccionados',
  'Ideas, made real.': 'Ideas hechas realidad.',
  'Design / Production / Experience': 'Diseño / Producción / Experiencia',
  'Project': 'Proyecto',
  'Explore the story': 'Explora la historia',
  'What I do': 'Lo que hago',
  'Different disciplines.': 'Distintas disciplinas.', 'One curious mind.': 'Una mente curiosa.',
  'Let’s talk': 'Hablemos',
  'The person behind the practice': 'La persona detrás del trabajo',
  'CURIOSITY': 'LA CURIOSIDAD', 'MADE ME': 'ME HIZO', 'A CREATOR': 'CREADOR',
  'I’ve always been creative, and technology has always come naturally to me. Curiosity connected the two.': 'Siempre he sido creativo y la tecnología siempre se me ha dado bien. La curiosidad conectó ambas cosas.',
  'Growing up, I found myself constantly reading, learning and exploring whatever captured my attention. The more I learned, the more questions I had—and eventually, those questions became things I wanted to create.': 'Desde pequeño, siempre estaba leyendo, aprendiendo y explorando todo lo que despertaba mi interés. Cuanto más aprendía, más preguntas tenía; con el tiempo, esas preguntas se convirtieron en cosas que quería crear.',
  'What excites me most is the possibility of building technology that can make someone’s everyday life a little better.': 'Lo que más me entusiasma es la posibilidad de crear tecnología que mejore un poco la vida cotidiana de alguien.',
  'Ultimately, I want to invent things.': 'Al final, quiero inventar cosas.',
  'Creator / Designer / Developer / Producer': 'Creador / Diseñador / Desarrollador / Productor',
  'What’s next': 'Lo que viene', 'Back to daylight ↑': 'Volver al inicio ↑',
  'LET’S MAKE': 'CREEMOS', 'SOMETHING': 'ALGO',
  'Have an idea, a problem to solve, or something you want to create? Tell me about it.': '¿Tienes una idea, un problema que resolver o algo que quieres crear? Cuéntamelo.',
  'Start a project': 'Inicia un proyecto', 'Start a project ↗': 'Inicia un proyecto ↗',
  'CREATIVE TECHNOLOGY STUDIO': 'ESTUDIO DE TECNOLOGÍA CREATIVA',
  'Creative Technology Studio': 'Estudio de tecnología creativa',
  'Creative Technology Studio · Miami, Florida': 'Estudio de tecnología creativa · Miami, Florida',
  'Menu': 'Menú', 'Close ×': 'Cerrar ×', 'Work': 'Trabajo', 'Services': 'Servicios', 'About': 'Sobre mí',
  'Designed & developed by Emilio Sierra · Miami, FL': 'Diseñado y desarrollado por Emilio Sierra · Miami, FL',
  'Inquiry preview': 'Vista previa de la consulta',
  'Email delivery is not connected yet. This form is for reviewing the inquiry experience; nothing will be sent or saved.': 'El envío de correo aún no está conectado. Este formulario permite revisar la experiencia de consulta; no se enviará ni guardará nada.',
  'Your name': 'Tu nombre', '(required)': '(obligatorio)', 'Email address': 'Correo electrónico',
  'Company / organization': 'Empresa / organización', '(optional)': '(opcional)',
  'What are you interested in?': '¿Qué te interesa?', '(choose any)': '(elige las opciones que quieras)',
  'Tell me about your project': 'Cuéntame sobre tu proyecto',
  'When are you hoping to get started?': '¿Cuándo te gustaría empezar?',
  'Review inquiry preview': 'Revisar la consulta',
  'What are you trying to create, improve, or solve?': '¿Qué quieres crear, mejorar o resolver?',
  'Something Else': 'Algo más',
  'Preview reviewed. Your inquiry has not been sent. Email delivery must be configured before this form can accept inquiries.': 'Vista previa revisada. Tu consulta no se ha enviado. Es necesario configurar el correo antes de que este formulario pueda recibir consultas.',
  'Project inquiry': 'Consulta de proyecto', 'WHAT ARE': '¿QUÉ', 'WE MAKING': 'CREAMOS', '?': '?',
  'Tell me a little about your project.': 'Cuéntame un poco sobre tu proyecto.',
  'The inquiry experience is in preview while email delivery is being set up.': 'La experiencia de consulta está en vista previa mientras se configura el envío de correo.',
  '← All work': '← Todos los trabajos',
  'Case-study draft · Media, credits and publication details pending approval.': 'Borrador del proyecto · Imágenes, créditos y detalles de publicación pendientes de aprobación.',
  'The story': 'La historia', 'Next project ↗': 'Siguiente proyecto ↗',
  'A different direction': 'Otra dirección', 'Nothing here.': 'Aquí no hay nada.',
  'Plenty ahead.': 'Mucho por descubrir.', 'Return to the studio →': 'Volver al estudio →',
  'Skip to content': 'Saltar al contenido',
  'Emilio Sierra home': 'Inicio de Emilio Sierra', 'Main navigation': 'Navegación principal',
  'Site navigation': 'Navegación del sitio', 'Mobile navigation': 'Navegación móvil', 'Footer navigation': 'Navegación del pie de página',
  'Digital': 'Digital', 'Visual': 'Visual', 'Motion': 'Movimiento',
  'Web + App Design & Development': 'Diseño y desarrollo web y de aplicaciones',
  'I design and build websites, applications and digital tools around the people who use them.': 'Diseño y desarrollo sitios web, aplicaciones y herramientas digitales pensando en quienes las usan.',
  'Websites / Web apps / UI + UX / Digital tools': 'Sitios web / Aplicaciones web / UI + UX / Herramientas digitales',
  'Graphic Design': 'Diseño gráfico',
  'Visual design created for digital experiences, communication and physical production.': 'Diseño visual para experiencias digitales, comunicación y producción física.',
  'Digital graphics / Production artwork / Visual design': 'Gráficos digitales / Arte para producción / Diseño visual',
  'Video Production': 'Producción de video',
  'Video capture, live streaming and production backed by hands-on live broadcasting experience.': 'Grabación de video, transmisiones en vivo y producción con experiencia práctica en emisiones en directo.',
  'Video / Live streaming / Production / Editing': 'Video / Transmisiones en vivo / Producción / Edición',
  'From pixels to physical.': 'De píxeles a objetos.', 'Theatrical prop packaging': 'Empaques para utilería teatral',
  'Graphic design / Production artwork': 'Diseño gráfico / Arte para producción',
  'Recreating vintage packaging for a life on stage.': 'Recreando empaques antiguos para darles vida en el escenario.',
  'Artwork & finished prop photographs pending': 'Arte y fotografías de la utilería terminada pendientes',
  'A small object. Every detail matters.': 'Un objeto pequeño. Cada detalle cuenta.',
  'I recreated a vintage cigarette-box graphic in Adobe Photoshop for a designer to use in a theatrical prop. The artwork needed to work as a package, with components arranged to wrap around a physical form.': 'Recreé el diseño de una antigua caja de cigarrillos en Adobe Photoshop para que un diseñador lo utilizara en una pieza de utilería teatral. El arte debía funcionar como empaque, con elementos dispuestos para envolver una forma física.',
  'Reference to production artwork.': 'De la referencia al arte para producción.',
  'The process brought together rulers, measurement, graphic reconstruction and layout techniques. I worked on the graphic recreation and production artwork; the designer used it to produce the physical prop.': 'El proceso combinó reglas, mediciones, reconstrucción gráfica y técnicas de composición. Me encargué de la recreación gráfica y del arte para producción; el diseñador lo utilizó para fabricar la pieza de utilería.',
  'From digital to physical.': 'De lo digital a lo físico.',
  'The reference, artwork and finished prop will be shown here once the media and publication permissions are confirmed.': 'La referencia, el arte y la utilería terminada se mostrarán aquí cuando se confirmen los materiales y los permisos de publicación.',
  'Made for the moment.': 'Creado para el momento.',
  'South Florida live sports broadcasting': 'Transmisiones deportivas en vivo en el sur de Florida',
  'Video production / Live broadcasting': 'Producción de video / Transmisiones en vivo',
  'Behind the scenes of live high-school baseball in South Florida.': 'Detrás de cámaras del béisbol de secundaria en vivo en el sur de Florida.',
  'Broadcast & behind-the-scenes media': 'Imágenes de transmisión y detrás de cámaras',
  'Before the first pitch.': 'Antes del primer lanzamiento.',
  'Working with a small broadcast crew across Miami-Dade and Broward County, I helped set up the production site, prepare equipment and check that systems were ready to go live.': 'Con un pequeño equipo de transmisión en los condados de Miami-Dade y Broward, ayudé a montar el sitio de producción, preparar los equipos y comprobar que los sistemas estuvieran listos para salir al aire.',
  'An experience unfolding in real time.': 'Una experiencia en tiempo real.',
  'During broadcasts, I switched camera feeds, monitored audio and the YouTube live feed, followed channel activity and interacted with viewers. After the game, I helped break down the production site and equipment.': 'Durante las transmisiones, alternaba las señales de las cámaras, supervisaba el audio y la transmisión de YouTube, seguía la actividad del canal e interactuaba con los espectadores. Después del partido, ayudaba a desmontar el sitio de producción y los equipos.',
  'Creating in the live environment.': 'Crear en un entorno en vivo.',
  'This work taught me to operate experiences that had to function in real time. Broadcast excerpts and production photographs will be added once the media and permissions are confirmed.': 'Este trabajo me enseñó a gestionar experiencias que debían funcionar en tiempo real. Se añadirán fragmentos de las transmisiones y fotografías de producción cuando se confirmen los materiales y los permisos.',
  'Emilio Sierra using his smartphone beside sunlit windows and tropical greenery.': 'Emilio Sierra usando su teléfono junto a ventanas iluminadas por el sol y vegetación tropical.',
  'Emilio Sierra standing indoors in a white shirt, light blue tie and beige trousers.': 'Emilio Sierra de pie en un interior con camisa blanca, corbata azul claro y pantalones beige.',
  'Gauloises Blondes replica cigarette carton guide showing flat artwork, assembly steps and views of the finished blue package.': 'Guía de una réplica de un empaque de cigarrillos Gauloises Blondes con el arte plano, los pasos de montaje y vistas del empaque azul terminado.',
  'Behind the live broadcast: South Florida high-school baseball production collage showing channel branding, scoreboard graphics, live switching, scorekeeping and camera equipment.': 'Detrás de la transmisión en vivo: collage de producción de béisbol de secundaria en el sur de Florida con identidad del canal, gráficos del marcador, cambio de cámaras, anotación y equipos de cámara.',
};
